name: Allure Report

on:
  push:
    branches: [ "qa-kotlin-6-1" ]

permissions:
  contents: write

jobs:
  allure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run Tests
        run: ./gradlew test
        continue-on-error: true

      - name: Install Allure CLI
        run: sudo npm install -g allure-commandline --save-dev

      - name: Generate Report
        run: |
          allure generate app/build/allure-results -o reports --clean

      - name: Commit and Push Report
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add reports/
          git commit -m "docs: update allure report [skip ci]" || echo "No changes"
          git push origin HEAD:${{ github.ref }}